//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flexiFixAppoval
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public string Obj { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Status { get; set; }
        public string DeclineReason { get; set; }
    }
}
