//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flexiFixAppoval
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public long ID { get; set; }
        public string DBS { get; set; }
        public string SafeGuarding { get; set; }
        public string FirstAid { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string KnownAs { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string Telephone { get; set; }
        public string AlternateTelephone { get; set; }
        public string Email { get; set; }
        public string NationalInsuranceNumber { get; set; }
        public string Qualifications { get; set; }
        public string DrivingLicense { get; set; }
        public string RegisteredDisabled { get; set; }
        public string ReferenceName1 { get; set; }
        public string ReferencePhoneNumber1 { get; set; }
        public string ReferenceEmail1 { get; set; }
        public string ReferenceName2 { get; set; }
        public string ReferencePhoneNumber2 { get; set; }
        public string ReferenceEmail2 { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string StaffID { get; set; }
        public string PhoneModel { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> RoleID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string Status { get; set; }
        public string Picture { get; set; }
        public string EmergencyContactPhoneNo { get; set; }
        public string ReferenceCompanyName1 { get; set; }
        public string ReferenceRelationship1 { get; set; }
        public string ReferenceCanContact1 { get; set; }
        public string ReferenceCompanyName2 { get; set; }
        public string ReferenceRelationship2 { get; set; }
        public string ReferenceCanContact2 { get; set; }
        public bool ExistingStaff { get; set; }
        public string OfficialEmail { get; set; }
        public string EmploymentType { get; set; }
        public decimal NumberOfLeaveDays { get; set; }
        public int LeaveType { get; set; }
        public string Token { get; set; }
    }
}
